In [2]:
print("Hello world , how are you")

Hello world , how are you


<ul>
    <li>Apple</li>
    <li>Banana</li>
    <li>Cherry</li>
</ul>

<h1>Hii Everyone</h1>

# ceeya

In [3]:
## bye

## bye


In [4]:
import numpy as np

In [5]:
a1 = np.array([1,2,"a","b"])

In [40]:
type(a1)

numpy.ndarray

In [7]:
type(a1)

numpy.ndarray

In [8]:
l=[1,2,"a","b"]

In [9]:
type(l)

list

In [18]:
#properties of an array
a = np.array([10,20,30,40,"i"])

In [11]:
a.ndim

1

In [12]:
a.shape

(4,)

In [13]:
a.dtype

dtype('int32')

In [20]:
a.size

5

In [19]:
a.itemsize

44

In [21]:
# different ways of CREATING ARRAY
np.arange(10,22,2)

array([10, 12, 14, 16, 18, 20])

In [22]:
np.arange(20)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
#Multi dimension

np.arange(30).reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
np.array(np.random.randn(5),dtype="int")

array([ 0, -1,  0,  1, -1])

In [29]:
np.zeros(2)

array([0., 0.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
# to get positive values give abs function
abs(np.array(np.random.randn(5),dtype="int"))

array([0, 0, 1, 0, 0])

In [39]:
np.array(np.random.randn(5))

array([1.63457042, 0.6168914 , 1.06887475, 1.02245461, 1.33662748])

In [44]:
#multi dimension
np.array([[1,2,3],[4,6,5]])

array([[1, 2, 3],
       [4, 6, 5]])

In [45]:
# 2 rows 3 cols
np.arange(10,22,2).reshape(2,3)

array([[10, 12, 14],
       [16, 18, 20]])

In [46]:
# 3 rows 2cols
np.arange(10,22,2).reshape(3,2)

array([[10, 12],
       [14, 16],
       [18, 20]])

In [62]:
b=np.random.randn(20).reshape(4,5)

In [51]:
np.array(np.random.randn(20),dtype="int").reshape(4,5)

array([[ 0,  0, -2,  1,  0],
       [ 0, -2,  0,  0,  2],
       [ 0,  0,  0,  1,  0],
       [ 0,  0,  0,  0, -1]])

In [52]:
abs(np.array(np.random.randn(20),dtype="int").reshape(4,5))

array([[0, 1, 0, 0, 1],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 2]])

In [54]:
a=np.arange(30).reshape(2,3,5)

In [55]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [56]:
a[1]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [57]:
a[1][2]

array([25, 26, 27, 28, 29])

In [58]:
a[1][2][4]

29

In [60]:
a.dtype

dtype('int32')

In [61]:
a.itemsize

4

In [63]:
b

array([[ 1.2934906 , -0.32987824, -0.04590216,  0.74258175, -1.4499242 ],
       [ 1.46330606, -0.36530672,  1.44248537, -1.27489189, -0.20160183],
       [-2.31148269, -1.15804688,  1.0077064 ,  0.53760404, -0.15323078],
       [-0.3194942 ,  0.87203706,  0.23691371,  1.34896422, -0.783863  ]])

In [64]:
b.dtype

dtype('float64')

In [65]:
b.itemsize

8

In [66]:
b.size

20

In [2]:
import numpy as np

In [4]:
a = np.arange(1,13).reshape(2,2,3)

In [5]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [7]:
#axis=0 means outer dimensions addition means1 row of 1 bracket with 1st one with other one bracket
a.sum(axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [8]:
#axis=1 means first first place elements are added to first place elements in the two brAckets of the same matrix
a.sum(axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [9]:
#axis=2 means means first bracket is internally added second bracket is internamlly added and given as 1st & 2nd row elements& similarly for the 2nd row also
a.sum(axis=2)

array([[ 6, 15],
       [24, 33]])

In [11]:
a.max()

12

In [12]:
a.min()

1

In [13]:
a.mean()

6.5

In [14]:
a.var()

11.916666666666666

In [15]:
a.sum()

78

In [16]:
# Numpy functions

In [17]:
a = np.arange(1,21)

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [20]:
np.mean(a)

10.5

In [21]:
np.median(a)

10.5

In [30]:
a= np.array([10,15,20,25,30,35,40,45,600,700])

In [24]:
# to get quantile function

In [32]:
q1 = np.quantile(a,0.25)

In [33]:
q3 = np.quantile(a,0.75)

In [34]:
print(q1)

21.25


In [35]:
print(q3)

43.75


In [36]:
print(q1,q3)

21.25 43.75


In [37]:
iqr = q3-q1

In [38]:
iqr

22.5

In [44]:
#upper_whisker
upper_range = q3 + 1.5*iqr

In [40]:
#lowerr_whisker
lower_range = q1 - 1.5*iqr

In [41]:
upper_range

77.5

In [42]:
lower_range

-12.5

In [45]:
# Math functions

In [47]:
np.sin(90)

0.8939966636005579

In [48]:
np.cos(0)

1.0

In [49]:
np.log(1)

0.0

In [50]:
np.log10(10)

1.0

In [51]:
np.sqrt(625)

25.0

In [52]:
np.log(np.log10(5))

-0.35814744992084513

In [53]:
# Reducing skewness

In [54]:
a = np.array([1,2,2,3,3,3,4,4,16,20,25])

In [55]:
a

array([ 1,  2,  2,  3,  3,  3,  4,  4, 16, 20, 25])

In [57]:
np.mean(a)

7.545454545454546

In [58]:
np.median(a)

3.0

In [59]:
from scipy.stats import skew

In [60]:
skew(a)

1.1712731595847037

In [61]:
a = np.sqrt(a)

In [62]:
a

array([1.        , 1.41421356, 1.41421356, 1.73205081, 1.73205081,
       1.73205081, 2.        , 2.        , 4.        , 4.47213595,
       5.        ])

In [63]:
skew(a)

0.9630668329521322

In [68]:
a1 = np.arange(10,16).reshape(3,2)
a1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [70]:
a2 = np.arange(16,22).reshape(3,2)
a2

array([[16, 17],
       [18, 19],
       [20, 21]])

In [67]:
#rows are concatenated axis= 0
np.concatenate([a1,a2])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [71]:
# coloum wise conctenation
np.concatenate([a1,a2],axis = 1)

array([[10, 11, 16, 17],
       [12, 13, 18, 19],
       [14, 15, 20, 21]])

In [72]:
np.unique([1,2,2,3])

array([1, 2, 3])

In [73]:
np.unique([22,20,22,22,26,20],return_counts= True)

(array([20, 22, 26]), array([2, 3, 1], dtype=int64))

In [74]:
a = np.array(["a","a","b","b","c"])

In [75]:
a

array(['a', 'a', 'b', 'b', 'c'], dtype='<U1')

In [76]:
np.unique(a,return_counts=True)

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [79]:
# Indexing & Slicing
a = np.arange(10,20).reshape(5,2)

In [80]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [81]:
a[0]

array([10, 11])

In [82]:
a[0][1]

11

In [84]:
a[3,1]

17

In [85]:
a[0,]

array([10, 11])

In [87]:
# slicing 2& 4 are indexes
a[2:4]

array([[14, 15],
       [16, 17]])

In [88]:
a = np.arange(9).reshape(3,3)

In [89]:
a


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [90]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

In [91]:
a[[0,2]]

array([[0, 1, 2],
       [6, 7, 8]])

In [94]:
#starting to end in a step of size two
a[[0,2],::2]

array([[0, 2],
       [6, 8]])

In [95]:
a[::2,::2]

array([[0, 2],
       [6, 8]])

In [96]:
# boolean indexing

In [97]:
a>4

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [98]:
a[a>4]

array([5, 6, 7, 8])

In [99]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [106]:
b1 = np.array([1,2,3,4]).reshape(2,2) 
b2 = np.array([5,6,7,8]).reshape(2,2)

In [112]:
b1


array([[1, 2],
       [3, 4]])

In [109]:
b1 * b2

array([[ 5, 12],
       [21, 32]])

In [111]:
np.dot(b1,b2)

array([[19, 22],
       [43, 50]])

In [113]:
b2

array([[5, 6],
       [7, 8]])

In [114]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [115]:
a1+a2

array([5, 7, 9])

In [116]:
# a scalar and vectior cant be multiplied but converting scalar 2 into [2,2,2]vector this works is known as vectorization..
a1 * 2

array([2, 4, 6])

### Broadcasting

In [118]:
a1= np.array([1,2,3,4,5,6]).reshape(3,2)

In [119]:
a2=np.array([4,4])

In [120]:
a1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [121]:
a2

array([4, 4])

In [124]:
# here matrix is multiplied to a vector coverting into matrix as each element as 4 which is known as broadcastig
a1*a2

array([[ 4,  8],
       [12, 16],
       [20, 24]])